# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: S3RDV LLC
email: contact@s3rdv.com
description: >-
  S3RDV LLC is a leading provider of Solana blockchain infrastructure services, 
  operating the CatalystX validator and supporting the network with over 2000 miles 
  of 100 gigabit connectivity through doublezero.
baseurl: ""
url: "https://s3rdv.com"

# Social links
twitter_username: CatalystX_sol
github_username: T3chie-404

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache

# Custom settings
company_info:
  name: "S3RDV LLC"
  founded: "2023"
  focus: "Solana Blockchain Infrastructure"
  services:
    - "CatalystX Solana Validator Operations"
    - "Network Infrastructure Support"
    - "Blockchain Infrastructure Consulting"

# Dark theme settings
dark_theme: true
primary_color: "#14F195"  # Solana green
secondary_color: "#9945FF"  # Solana purple
accent_color: "#FF6B35"  # Orange accent
background_color: "#0A0A0A"  # Very dark background
surface_color: "#1A1A1A"  # Dark surface
text_color: "#E0E0E0"  # Light text
text_muted: "#A0A0A0"  # Muted text

# Validator information
validator_info:
  name: "CatalystX"
  vote_account: "ErvMUdtMC7AX55zKdYSyy4DnWNCrTsWn5GwprSG7ocnx"
  commission: "5%"
  uptime: "99.99%"
  performance_score: "100%"

# Network infrastructure
infrastructure:
  connectivity: "2000+ miles of 100 gigabit connectivity"
  partner: "doublezero"
  support: "Solana network infrastructure"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
